media:
  input: src/assets/img
  output: /
content:
  - name: posts
    label: Posts
    path: src/content/blog/posts
    type: collection
    view:
      fields: [ title, date, topics, published ]
    exclude: [ posts.11tydata.js ]
    fields:
      - name: title
        label: Title
        type: string
        description: Title of the post
      - name: date
        label: Date
        type: date
        description: Post publication date
      - name: topics
        label: Topics
        type: select
        description: Topics (tags) for the post
        options:
          multiple: true
          creatable: true
          values: [links, likes]
      - name: body
        label: Body
        type: text
        description: Post body
  - name: galleries
    label: Galleries
    type: collection
    format: json
    filename: {title}
    path: src/_data/galleries
    fields: 
      - name: title
        label: Title
        description: Title of the gallery
        type: string
      - name: description
        label: Description
        description: Description of the gallery contents
        type: text
      - name: published
        label: Published
        description: Whether or not to include the gallery on the site
        type: boolean
      - name: images
        label: Images
        description: Images in the gallery
        type: object
        list: true
        fields:
          - name: title
            label: Title
            type: string
          - name: img
            label: Image Link
            type: string
            description: Hyperlink to the image file
            pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
          - name: alt
            label: Alt-Text
            description: An accessible description of the image
            type: string
            required: true
          - name: caption
            label: Caption
            description: Text to display below the image
            type: text
          - name: artist
            label: Artist
            description: Credit the creator of this image
            type: reference
            required: false
            options:
              collection: artists
              search: "name"
              value: "{name}"
              label: "{name}"
          - name: license
            label: License
            type: select
            options: 
              values: ["CCO", "artist"]
          - name: sensitive
            label: Sensitive
            description: If selected, censor the image preview
            type: boolean
            default: false
          - name: topics
            label: Topics
            description: Topics (tags) for this image
            type: select
            creatable: true
            multiple: true
            options:
              values: ["oc", "fursona", "furry", "jamie", "amani", "train", "illustration", "digital", "traditional"]

  - name: images
    label: Images
    path: src/_data/images.json
    type: file
    list: true
    fields:
      - name: title
        label: Title
        type: string
      - name: img
        label: Img
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: alt
        label: Alt-text
        type: string
      - name: description
        label: Description
        type: text
      - name: artist
        label: Artist
        type: reference
        required: false
        options:
          collection: artists
          search: "name"
          value: "{name}"
          label: "{name}"
      - name: license
        label: License
        type: select
        options: 
          values: ["CCO", "artist"]
  - name: metadata
    label: Metadata
    path: src/_data/meta.json
    type: file
    fields:
      - name: author
        label: Author
        type: string
      - name: base
        label: Base
        type: string
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
  - name: artists
    label: Artists
    path: src/_data/artists
    type: collection
    fields:
      - name: name
        label: Name
        type: string
      - name: handle
        label: Handle
        type: string
      - name: site
        label: Site
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
