content:
  - name: posts
    label: Posts
    path: src/content/blog/posts
    type: collection
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
        description: Displays post if published
      - name: title
        label: Title
        type: string
        description: Title of the post
      - name: date
        label: Date
        type: date
        description: Post publication date
      - name: topics
        label: Topics
        type: select
        description: Topics (tags) for the post
        options:
          multiple: true
          creatable: true
          values: ["", links, likes]
      - name: content
        label: Content
        type: rich-text
        description: Post body
  - name: images
    label: Images
    path: src/_data/images.json
    type: file
    list: true
    fields:
      - name: title
        label: Title
        type: string
      - name: img
        label: Img
        type: string
      - name: alt
        label: Alt-text
        type: string
      - name: description
        label: Description
        type: text
      - name: artist
        label: Artist
        type: reference
        options:
          collection: artists
          search: "name"
          value: "{name}"
          label: "{name}"
      - name: license
        label: License
        type: select
        options: ["CCO", "artist"]
  - name: metadata
    label: Metadata
    path: src/_data/meta.json
    type: file
    fields:
      - name: author
        label: Author
        type: string
      - name: base
        label: Base
        type: string
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
  - name: artists
    label: Artists
    path: src/_data/artists.json
    type: file
    list: true
    fields:
      - name: name
        label: Name
        type: string
      - name: handle
        label: Handle
        type: string
      - name: site
        label: Site
        type: string
