media:
  input: src/assets/img
  output: /
content:
  - name: posts
    label: Posts
    path: src/content/blog/posts
    type: collection
    view:
      fields: [ title, date, headerImage, topics, published ]
    exclude: [ posts.11tydata.js ]
    fields:
      - name: title
        label: Title
        type: string
        description: Title of the post
      - name: date
        label: Date
        type: date
        description: Post publication date
      - name: headerImage
        label: Image
        description: Post header image
        required: false
        type: object
        fields:
        - name: src
          label: Image
          description: Image href
          type: string
        - name: alt
          label: Alt-text
          description: Image alt text
          type: string
        - name: format
          label: Threshold
          description: Apply the Threshold filter to this imaage
          default: true
      - name: topics
        label: Topics
        type: select
        description: Topics (tags) for the post
        options:
          multiple: true
          creatable: true
          values: [links, likes, weeklies]
      - name: description
        label: Description
        description: Excerpt to be displayed in the post preview
        type: text
      - name: body
        label: Body
        type: text
        description: Post body

  - name: galleries
    label: Galleries
    type: collection
    format: json
    filename: '{primary}.json'
    path: src/_data/galleries
    fields: 
      - name: title
        label: Title
        description: Title of the gallery
        type: string
      - name: description
        label: Description
        description: Description of the gallery contents
        type: text
      - name: published
        label: Published
        description: Whether or not to include the gallery on the site
        type: boolean
      - name: collections
        label: Collections
        description: Collections in this gallery
        list: true
        type: object
        fields:
          - name: title
            label: Title
            type: string
          - name: description
            label: Description
            type: string
          - name: images
            label: Images
            description: Images in the collection
            type: object
            list: true
            fields:
              - name: title
                label: Title
                type: string
              - name: img
                label: Image Link
                type: string
                description: Hyperlink to the image file
                pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
              - name: alt
                label: Alt-Text
                description: An accessible description of the image
                type: string
                required: true
              - name: caption
                label: Caption
                description: Text to display below the image
                type: text
              - name: artist
                label: Artist
                description: Credit the creator of this image
                type: reference
                required: false
                options:
                  collection: artists
                options:
                  collection: artists
                  search: "name"
                  value: "{name}"
                  label: "{name}"
              - name: license
                label: License
                type: select
                multiple: false
                options: 
                  values: ["CC0", "artist"]
              - name: sensitive
                label: Sensitive
                description: If selected, censor the image preview
                type: boolean
                default: false
              - name: topics
                label: Topics
                description: Topics (tags) for this image
                type: select
                options:
                  values: ["oc", "fursona", "furry", "jamie", "amani", "train", "illustration", "digital", "traditional"]
              - name: cover
                label: Cover Image
                type: boolean
                default: false
                description: Use this image as the cover of the collection

  - name: metadata
    label: Metadata
    path: src/_data/meta.json
    type: file
    fields:
      - name: author
        label: Author
        type: string
      - name: birthday
        label: Birthday
        type: date
      - name: base
        label: Base
        type: string
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string

  - name: artists
    label: Artists
    path: src/_data/artists
    format: json
    filename: '{primary}.json'
    primary: name
    type: collection
    fields:
      - name: name
        label: Name
        type: string
      - name: handle
        label: Handle
        type: string
      - name: site
        label: Site
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$

  - name: badges
    label: badges
    path: src/_data/badges.json
    format: json
    type: file
    fields:
      - name: badges
        label: Badges
        type: object
        list: true
        fields: 
          - name: src
            label: Badge Source
            description: Link to badge image
            type: string
          - name: alt
            label: Badge Alt-text
            description: Text description of the badge
            type: string
          - name: href
            label: Badge Link
            required: false
            description: (Optional) Site the badge links too
            type: string  
          - name: title
            label: Title
            required: false
            description: (Optional) Text to display on hover
            type: string
          - name: author
            label: Author
            required: false
            description: (Optional) Creator of this badge
            type: object
            fields: 
              - name: name
                label: Author Name
                type: string
                description: Name of the creator of this badge
              - name: site
                label: Author Site
                type: string
                description: Link to the creator's site
          - name: footer
            label: Display in footer
            type: boolean
            default: false
            description: If checked, displays this badge in the site footer
