name: Deploy
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies and build
        run: |
          yarn
          yarn run build
      - name: Deploy to server
        # uses: ...
