backend:
  name: github
  repo: itsfriendmeat/friendmeat.org
  branch: cms

media_folder: "/static"

collections: 
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: ""
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog/post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Image", name: "img", widget: "string"}
      - {label: "Image Alt Text", name: "alt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", time_format: false, date_format: "YYYY-MM-DD", format: "YYYY-MM-DD" }
      - {label: "Tags", name: "tags", widget: "list", default: ["posts"]}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "galleries"
    label: "Galleries"
    files:
      - label: "Galleries"
        name: "galleries"
        label_singular: "Gallery"
        create: true
        file: "src/_data/galleries.json"
        fields:
          - label: "Galleries"
            name: "galleries"
            label_singular: "Gallery"
            widget: "list"
            fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Description", name: "description", widget: "string"}
            - label: Image
              name: image
              widget: "list"
              create: true
              fields: 
                    - {label: "Url", name: "src", widget: "string"}
                    - {label: "Description", name: "alt", widget: "string"}
                    - {label: "Artist", name: "artist", widget: "string", required: false}
                    - {label: "Artist Site", name: "site", widget: "string", required: false}