name: Test build

on:
  pull_request:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup pnpm
      uses: pnpm/action-setup@v4.1.0
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: latest
        cache: 'pnpm'
    - name: Install deps and build
      run: |
        pnpm install
        IMAGES_STATS_ONLY=true pnpm exec eleventy --config=eleventy.config.js
